#!/bin/bash

../noinput escape.exe literals.exe unsigned.exe scope_levels.exe convs.exe inits.exe ref-ex.exe dbl_ptr.exe compounddecls.exe decl-ex.exe

echo "Sales_data:" && ./Sales_data.exe < data/add_item
